<?php
/**
 * Ready Studio SEO Engine - Module: Robots.txt Generator
 *
 * v13.0: CRITICAL PARSE ERROR FIX
 * Rewrote the `get_task_prompt` function to use sprintf with
 * single-quoted strings (') to prevent any and all syntax errors
 * caused by complex string concatenation.
 *
 * @package   ReadyStudio
 * @version   13.0.0
 * @author    Fazel Ghaemi
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class ReadyStudio_Module_Robots {

	/**
	 * Core API instance (injected).
	 * @var ReadyStudio_Core_API
	 */
	private $api;

	/**
	 * Settings for this module.
	 * @var array
	 */
	private $options;

	/**
	 * Constructor.
	 *
	 * @param ReadyStudio_Core_Loader $core_loader The main loader instance.
	 */
	public function __construct( $core_loader ) {
		$this->init( $core_loader );
	}

	/**
	 * Initialize the module and inject dependencies.
	 *
	 * @param ReadyStudio_Core_Loader $core_loader The main loader instance.
	 */
	public function init( $core_loader ) {
		// Inject dependencies
		$this->api = $core_loader->api;
		
		// Load this module's specific options
		$this->options = get_option( 'promptseo_robots_options', [] );

		// Register hooks
		add_action( 'admin_menu', [ $this, 'register_menu' ], 30 );
		add_action( 'admin_init', [ $this, 'register_settings' ] );
		add_action( 'wp_ajax_rs_generate_robots', [ $this, 'ajax_handle_generate_robots' ] );
		add_action( 'wp_ajax_rs_write_physical_robots', [ $this, 'ajax_handle_write_physical' ] );

		// Only filter robots.txt if the module is enabled AND physical file is not in use
		if ( $this->is_enabled() && ! $this->is_physical_file_active() ) {
			add_filter( 'robots_txt', [ $this, 'filter_robots_txt' ], 100, 2 );
		}
	}

	/**
	 * Checks if the module is enabled in settings.
	 * @return bool
	 */
	private function is_enabled() {
		return isset( $this->options['robots_enabled'] ) && $this->options['robots_enabled'] === 'on';
	}

	/**
	 * Checks if a physical file exists.
	 * @return bool
	 */
	private function is_physical_file_active() {
		$robots_file = $this->get_robots_path();
		return file_exists( $robots_file );
	}

	/**
	 * Gets the absolute path to the robots.txt file.
	 * @return string
	 */
	private function get_robots_path() {
		return ABSPATH . 'robots.txt';
	}

	/**
	 * 1. Registers the "Robots.txt" submenu page.
	 */
	public function register_menu() {
		add_submenu_page(
			'promptseo_dashboard',
			'سازنده Robots.txt',
			'سازنده Robots.txt',
			'manage_options',
			'promptseo_robots',
			[ $this, 'render_page' ]
		);
	}

	/**
	 * 2. Registers the settings group for this module.
	 */
	public function register_settings() {
		register_setting(
			'promptseo_robots_group',
			'promptseo_robots_options',
			[ $this, 'sanitize_options' ]
		);

		add_settings_section(
			'rs_robots_main_section',
			null,
			null,
			'promptseo_robots'
		);
	}

	/**
	 * 3. Renders the HTML for the Robots.txt Generator page.
	 */
	public function render_page() {
		// Fetch fresh options
		$this->options = get_option( 'promptseo_robots_options', [] );
		$is_enabled = $this->is_enabled();
		$user_rules = isset( $this->options['custom_rules'] ) ? $this->options['custom_rules'] : '';
		$ai_rules = isset( $this->options['ai_rules'] ) ? $this->options['ai_rules'] : "# پیشنهادات AI در اینجا ظاهر می‌شوند...";
		
		$sitemap_url = home_url( '/sitemap_index.xml' );
		if ( class_exists( 'RankMath' ) ) {
			$sitemap_url = RankMath\Helper::get_home_url( 'sitemap_index.xml' );
		}
		
		// Check filesystem permissions
		$robots_path = $this->get_robots_path();
		$is_writable = wp_is_writable( $robots_path );
		$physical_exists = file_exists( $robots_path );
		$is_managed_by_us = $physical_exists ? ( strpos( @file_get_contents( $robots_path ), 'Generated by AI SEO' ) !== false ) : false;
		
		?>
		<div class="wrap rs-wrap settings-page" dir="rtl">
			
			<div class="rs-header">
				<h1>
					AI SEO
					<span class="rs-brand-family">از خانواده <strong>Ready Studio</strong></span>
				</h1>
			</div>

			<nav class="rs-tabs">
				<div class="rs-tab-link active">
					<span class="dashicons dashicons-media-text" style="margin-left: 5px;"></span>
					سازنده هوشمند Robots.txt
				</div>
			</nav>

			<form method="post" action="options.php" style="margin:0;">
				<?php settings_fields( 'promptseo_robots_group' ); ?>
				<?php wp_nonce_field( 'rs_nonce_action', 'rs_robots_nonce' ); ?>

				<div class="rs-tab-content active">
					
					<!-- Enable/Disable Toggle -->
					<table class="form-table">
						<tr valign="top">
							<th scope="row">فعال‌سازی مدیریت Robots.txt</th>
							<td>
								<div class="pseo-field">
									<label for="field-robots_enabled" class="rs-toggle-switch">
										<input 
											type="checkbox" id="field-robots_enabled" name="promptseo_robots_options[robots_enabled]" 
											<?php checked( $is_enabled ); ?>>
										<span class="rs-toggle-slider"></span>
									</label>
									<p class="description" style="display: inline-block; margin-right: 10px;">
										اجازه بده افزونه AI SEO فایل robots.txt مجازی وردپرس را مدیریت کند.
									</p>
									<p class="description"><strong>توجه:</strong> اگر از فایل فیزیکی استفاده می‌کنید، این گزینه نادیده گرفته می‌شود.</p>
								</div>
							</td>
						</tr>
					</table>
					
					<hr style="border: 0; border-top: 1px solid var(--g-border); margin: 20px 0;">

					<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
						
						<!-- Column 1: AI & User Rules -->
						<div>
							<!-- *** NEW: AI Prompt Field *** -->
							<div class="pseo-field">
								<label for="ai-prompt-field" style="font-weight: 600;">پرامپت سفارشی شما (دستور به AI)</label>
								<textarea id="ai-prompt-field" class="ai-brain-textarea" style="height: 100px; background: #fff; border-color: var(--rs-accent); direction: rtl; text-align: right;" placeholder="مثال: سایت را از دسترس تمام ایجنت ها خارج کن بجز گوگل"><?php echo esc_textarea( isset( $this->options['last_ai_prompt'] ) ? $this->options['last_ai_prompt'] : '' ); ?></textarea>
								<p class="ai-brain-desc">دستور خود را به زبان فارسی بنویسید. AI آن را به قوانین robots.txt تبدیل می‌کند.</p>

								<button type="button" id="rs-gen-robots-btn" class="pseo-btn btn-magic" style="width: auto; margin-top: 10px;">
									<span class="dashicons dashicons-superhero" style="margin-top:4px; margin-left: 5px;"></span>
									اجرای پرامپت و تولید قوانین
								</button>
								<div id="rs-robots-loader" class="rs-loader-wrap" style="display:none; margin: 10px 0 0 0;"><div class="spinner-rs"></div></div>
							</div>

							<div class="pseo-field">
								<label for="ai-rules" style="font-weight: 600;">قوانین تولید شده توسط AI</label>
								<textarea id="ai-rules" name="promptseo_robots_options[ai_rules]" class="ai-brain-textarea" style="height: 200px;"><?php echo esc_textarea( $ai_rules ); ?></textarea>
							</div>
							
							<div class="pseo-field">
								<label for="custom-rules" style="font-weight: 600;">قوانین سفارشی شما (ادغام دستی)</label>
								<textarea id="custom-rules" name="promptseo_robots_options[custom_rules]" class="ai-brain-textarea" style="height: 150px;"><?php echo esc_textarea( $user_rules ); ?></textarea>
								<p class="ai-brain-desc">این قوانین در انتهای فایل اضافه خواهند شد.</p>
							</div>
						</div>

						<!-- Column 2: Final Preview & Physical File Controls -->
						<div>
							<label style="font-weight: 600;">پیش‌نمایش فایل نهایی</label>
							<pre id="robots-preview" style="background: var(--rs-primary); color: #f0f0f0; padding: 15px; border-radius: var(--rs-radius-standard); height: 490px; overflow: auto; font-family: monospace; direction: ltr; text-align: left; border: 1px solid var(--g-border);"><?php
								// Generate live preview
								$preview_content = $this->get_robots_content();
								echo esc_html( $preview_content );
							?></pre>

							<!-- Physical File Management -->
							<div class"pseo-field" style="margin-top: 15px; background: var(--g-bg); padding: 15px; border-radius: var(--rs-radius-standard);">
								<h4 style="margin:0 0 10px 0; color: var(--rs-primary);">مدیریت فایل فیزیکی (Physical File)</h4>
								<?php if ( $is_writable ) : ?>
									<p class="description" style="color: var(--g-green); font-weight: 600;">✓ هاست شما قابل نوشتن است.</p>
									<?php if ( $physical_exists && ! $is_managed_by_us ) : ?>
										<p class="description" style="color: var(--g-red);"><b>هشدار:</b> یک فایل `robots.txt` فیزیکی وجود دارد که توسط این افزونه ساخته نشده است. نوشتن فایل، آن را بازنویسی (Overwrite) می‌کند.</p>
									<?php elseif ( $is_managed_by_us ) : ?>
										<p class="description" style="color: var(--g-green);">✓ فایل `robots.txt` فیزیکی توسط AI SEO مدیریت می‌شود.</p>
									<?php endif; ?>
									<button type="button" id="rs-write-robots-btn" class="pseo-btn btn-primary" style="width: auto; margin-top: 10px;">
										<span class="dashicons dashicons-download" style="margin-top:4px; margin-left: 5px;"></span>
										نوشتن فایل فیزیکی در هاست
									</button>
								<?php else : ?>
									<p class="description" style="color: var(--g-red); font-weight: 600;">
										✗ خطا: هاست شما قابل نوشتن نیست.
										<br>
										افزونه نمی‌تواند فایل `robots.txt` فیزیکی بسازد. لطفاً سطح دسترسی (permission) فایل ریشه (`/`) را بررسی کنید.
									</p>
								<?php endif; ?>
								<div id="rs-write-robots-result" style="margin-top: 10px; font-weight: 600; font-size: 13px;"></div>
							</div>
						</div>
					</div>
					
					<?php submit_button( 'ذخیره تنظیمات (فایل مجازی)', 'primary pseo-btn btn-generate' ); ?>
				</div>
			</form>
		</div>

		<script type="text/javascript">
		jQuery(document).ready(function($) {
			var $aiRules = $('#ai-rules');
			var $userRules = $('#custom-rules');
			var $preview = $('#robots-preview');
			var sitemap = "<?php echo esc_js( $sitemap_url ); ?>";

			// Function to update the preview <pre> tag
			function updatePreview() {
				var ai = $aiRules.val() || "# (AI rules pending)";
				var user = $userRules.val() || "# (No user rules)";
				var previewText = "# Generated by AI SEO (Ready Studio)\n\n" +
								  "# --- AI Generated Rules --- \n" + ai +
								  "\n\n# --- User Defined Rules --- \n" + user +
								  "\n\nSitemap: " + sitemap;
				$preview.text(previewText);
			}

			// Update preview live when typing
			$aiRules.on('input', updatePreview);
			$userRules.on('input', updatePreview);
			
			// --- AJAX for AI Generation (UPDATED) ---
			$('#rs-gen-robots-btn').on('click', function() {
				var $btn = $(this);
				var $loader = $('#rs-robots-loader');
				var nonce = $('#rs_robots_nonce').val();
				var ai_prompt = $('#ai-prompt-field').val(); // Get the new prompt

				if ( !ai_prompt ) {
					alert('لطفا یک دستور (پرامپت) برای AI بنویسید.');
					return;
				}

				$btn.prop('disabled', true);
				$loader.show();

				$.post(ajaxurl, {
					action: 'rs_generate_robots',
					nonce: nonce,
					ai_prompt: ai_prompt // Send the new prompt
				})
				.done(function(res) {
					if (res.success) {
						$aiRules.val(res.data.robots_text).trigger('input'); // Update textarea and trigger preview
					} else {
						alert('خطا: ' + (res.data.message || res.data));
					}
				})
				.fail(function() { alert('خطای سرور (AJAX Fail)'); })
				.always(function() {
					$btn.prop('disabled', false);
					$loader.hide();
				});
			});

			// --- AJAX for Writing Physical File ---
			$('#rs-write-robots-btn').on('click', function() {
				var $btn = $(this);
				var $resultDiv = $('#rs-write-robots-result');
				var nonce = $('#rs_robots_nonce').val();
				
				// Get content *directly from the preview*
				var content = $preview.text();

				if (!confirm("آیا مطمئن هستید که می‌خواهید فایل فیزیکی robots.txt را روی هاست خود بازنویسی کنید؟")) {
					return;
				}

				$btn.prop('disabled', true).text('در حال نوشتن...');
				$resultDiv.css('color', 'var(--g-text-light)').text('در حال ارسال درخواست به سرور...');

				$.post(ajaxurl, {
					action: 'rs_write_physical_robots',
					nonce: nonce,
					content: content // Send the final content to be written
				})
				.done(function(res) {
					if (res.success) {
						$resultDiv.css('color', 'var(--g-green)').text('✓ ' + res.data.message);
					} else {
						$resultDiv.css('color', 'var(--g-red)').text('✗ خطا: ' + (res.data.message || res.data));
					}
				})
				.fail(function() {
					$resultDiv.css('color', 'var(--g-red)').text('✗ خطای سرور (AJAX Fail)');
				})
				.always(function() {
					$btn.prop('disabled', false).text('نوشتن فایل فیزیکی در هاست');
				});
			});
		});
		</script>
		<?php
	}

	/**
	 * 4. Handles the AJAX request for the "Generate AI Rules" button.
	 * (UPDATED to receive the custom prompt)
	 */
	public function ajax_handle_generate_robots() {
		// Security checks
		if ( ! check_ajax_referer( 'rs_nonce_action', 'nonce', false ) ) {
			wp_send_json_error( [ 'message' => 'Invalid security token.' ] );
			return;
		}
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( [ 'message' => 'Permission denied.' ] );
			return;
		}

		// 1. Get the custom prompt from the user
		$ai_prompt = isset( $_POST['ai_prompt'] ) ? sanitize_textarea_field( $_POST['ai_prompt'] ) : 'Generate standard WordPress rules.';
		
		// 2. Build the task prompt
		$task_prompt = self::get_task_prompt( $ai_prompt );

		// 3. Call the Core API (Nexus Brain)
		if ( ! $this->api ) {
			wp_send_json_error( [ 'message' => 'خطای داخلی: ماژول API بارگذاری نشده است.' ] );
			return;
		}
		
		// We pass an empty content and use the site title
		$response = $this->api->call_gemini_text( $task_prompt, '', get_bloginfo( 'name' ) );

		// 4. Send response back to JavaScript
		if ( is_wp_error( $response ) ) {
			wp_send_json_error( [ 'message' => $response->get_error_message() ] );
		} else {
			// Save the prompt for next time
			$this->options['last_ai_prompt'] = $ai_prompt;
			update_option( 'promptseo_robots_options', $this->options );
			
			wp_send_json_success( $response );
		}
	}

	/**
	 * 5. Handles the AJAX request for the "Write Physical File" button.
	 */
	public function ajax_handle_write_physical() {
		// 1. Security Check
		if ( ! check_ajax_referer( 'rs_nonce_action', 'nonce', false ) ) {
			wp_send_json_error( [ 'message' => 'Invalid security token.' ] );
			return;
		}
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error( [ 'message' => 'Permission denied.' ] );
			return;
		}

		// 2. Get content from AJAX
		$content = isset( $_POST['content'] ) ? stripslashes( $_POST['content'] ) : '';
		if ( empty( $content ) ) {
			wp_send_json_error( [ 'message' => 'محتوا خالی بود.' ] );
			return;
		}

		// 3. Get path
		$robots_file_path = $this->get_robots_path();

		// 4. Initialize WP_Filesystem
		global $wp_filesystem;
		if ( ! $wp_filesystem ) {
			require_once( ABSPATH . 'wp-admin/includes/file.php' );
			WP_Filesystem();
		}

		// 5. Write the file
		if ( ! $wp_filesystem->put_contents( $robots_file_path, $content, FS_CHMOD_FILE ) ) {
			// Failure
			wp_send_json_error( [ 'message' => 'خطا در نوشتن فایل. آیا سطح دسترسی (Permission) درست است؟' ] );
		} else {
			// Success
			wp_send_json_success( [ 'message' => 'فایل robots.txt فیزیکی با موفقیت نوشته شد.' ] );
		}
	}


	/**
	 * 6. Builds the AI Task Prompt for generating robots.txt rules.
	 *
	 * *** SYNTAX ERROR FIXED (v13.0) ***
	 * This function now uses single-quoted strings and sprintf
	 * to prevent any possible parse errors from complex concatenation.
	 *
	 * @param string $user_prompt The user's natural language command.
	 * @return string The formatted task prompt.
	 */
	public static function get_task_prompt( $user_prompt ) {
		// Use single quotes for the template to avoid double-quote escaping issues.
		$template = '
        --- TASK: Generate robots.txt Rules from a User Prompt ---
        You are a world-class SEO technical expert for WordPress.
        Your job is to convert a user\'s natural language request into a professional, secure `robots.txt` file.

        --- USER\'S COMMAND ---
        "%s"

        --- BASE RULES (Always include these unless user overrides) ---
        1.  Block common WordPress sensitive areas:
            `Disallow: /wp-admin/`
            `Disallow: /wp-includes/`
            `Disallow: /readme.html`
            `Disallow: /license.txt`
            `Disallow: /xmlrpc.php`
        2.  **Crucially**, ALLOW `admin-ajax.php`:
            `Allow: /wp-admin/admin-ajax.php`
        3.  Block plugin and theme *directories* (for security and crawl budget):
            `Disallow: /wp-content/plugins/`
            `Disallow: /wp-content/themes/`
        4.  **Crucially**, ALLOW the uploads directory for images:
            `Allow: /wp-content/uploads/`
        5.  Block low-value pages and query parameters:
            `Disallow: /search/`
            `Disallow: /feed/`
            `Disallow: /comments/feed/`
            `Disallow: /?s=`
        6.  Add `User-agent: Googlebot-Image` and `Allow: /` for image crawling.
        
        --- INSTRUCTIONS ---
        1.  Start with the BASE RULES.
        2.  Modify the rules based on the USER\'S COMMAND.
            - If user says "Block all agents", respond with `User-agent: * \n Disallow: /`
            - If user says "Block Bing", add `User-agent: Bingbot \n Disallow: /`
        3.  Ensure the output is *only* the text for the robots file.
        
        Respond ONLY with the following JSON structure (no markdown):
        {
          "robots_text": "... (your generated rules here) ..."
        }
        
        Note: Use \n for newlines in the JSON string. Do NOT include the Sitemap URL in this text.
        ';
		
		// Safely insert the user prompt into the template.
		// We escape any single quotes *from the user* so it doesn't break our template.
		$safe_prompt = str_replace( "'", "\'", $user_prompt );
		return sprintf( $template, $safe_prompt );
	}

	/**
	 * 7. Generates the full robots.txt content (used for both virtual and physical).
	 *
	 * @return string The new robots.txt content.
	 */
	private function get_robots_content() {
		// Get saved rules
		$ai_rules = isset( $this->options['ai_rules'] ) ? $this->options['ai_rules'] : '';
		$user_rules = isset( $this->options['custom_rules'] ) ? $this->options['custom_rules'] : '';

		// Get sitemap URL
		$sitemap_url = home_url( '/sitemap_index.xml' );
		if ( class_exists( 'RankMath' ) ) {
			$sitemap_url = RankMath\Helper::get_home_url( 'sitemap_index.xml' );
		}

		// Build the final file
		$new_output = "# Generated by AI SEO (Ready Studio)\n\n";
		
		if ( ! empty( $ai_rules ) ) {
			$new_output .= "# --- AI Generated Rules --- \n";
			$new_output .= $ai_rules;
			$new_output .= "\n\n";
		}

		if ( ! empty( $user_rules ) ) {
			$new_output .= "# --- User Defined Rules --- \n";
			$new_output .= $user_rules;
			$new_output .= "\n\n";
		}

		$new_output .= "Sitemap: " . esc_url( $sitemap_url ) . "\n";
		
		// Use stripslashes to remove any escaping
		return stripslashes( $new_output );
	}

	/**
	 * 8. Filters the virtual robots.txt file output.
	 * Fired by 'robots_txt' filter.
	 *
	 * @param string $output The default robots.txt output.
	 * @param bool $public Whether the site is public.
	 * @return string The new robots.txt content.
	 */
	public function filter_robots_txt( $output, $public ) {
		// If module is disabled, return default
		if ( ! $this->is_enabled() ) {
			return $output;
		}
		
		// If a physical file exists, let it take precedence.
		if ( $this->is_physical_file_active() ) {
			return $output; // Return default (WP will yield to the physical file)
		}

		// Site is set to "Discourage search engines"
		if ( ! $public ) {
			return "User-agent: *\nDisallow: /";
		}

		// Generate and return the virtual content
		return $this->get_robots_content();
	}

	/**
	 * 9. Sanitizes the options for this module before saving.
	 *
	 * @param array $input Raw data from the form.
	 * @return array Sanitized data.
	 */
	public function sanitize_options( $input ) {
		// Get existing options to merge
		$output = get_option( 'promptseo_robots_options', [] );

		// Checkbox
		$output['robots_enabled'] = ( isset( $input['robots_enabled'] ) && $input['robots_enabled'] === 'on' ) ? 'on' : 'off';
		
		// AI-generated rules
		if ( isset( $input['ai_rules'] ) ) {
			$output['ai_rules'] = sanitize_textarea_field( $input['ai_rules'] );
		}

		// User-defined rules
		if ( isset( $input['custom_rules'] ) ) {
			$output['custom_rules'] = sanitize_textarea_field( $input['custom_rules'] );
		}
		
		// We don't save 'last_ai_prompt' here, it's saved via AJAX
		// to prevent it from being overwritten on a simple settings save.

		return $output;
	}

} // End class ReadyStudio_Module_Robots

// Instantiate the module by hooking into the core loader
add_action( 'rs_core_loaded', function( $core_loader ) {
	new ReadyStudio_Module_Robots( $core_loader );
} );